GO
ALTER PROCEDURE [dbo].[PROD_INS_STYLE_INFO]
(
	@STYLEID INT,
	@CMDTYPE VARCHAR(25),
	@STYLE VARCHAR(25),
	@FABRICID INT,
	@COLORID INT,
	@TYPEID INT,
	@PRDQNTY DECIMAL(10, 0),
    @VAP VARCHAR(30) = NULL,
	@IDOUTPUT VARCHAR(10) OUTPUT
)
AS
BEGIN
	BEGIN TRY
			SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
			BEGIN TRANSACTION UPSERT
				INSERT INTO PRD_STYLE_HEADER VALUES(@FABRICID, @STYLE,@PRDQNTY,@VAP);
				SET @IDOUTPUT = @@IDENTITY;

				INSERT INTO PRD_STYLE_COLOR VALUES(@IDOUTPUT, @COLORID);

				INSERT INTO PRD_STYLE_TYPE VALUES(@IDOUTPUT, @TYPEID);

			COMMIT TRANSACTION UPSERT
		END TRY
		BEGIN CATCH
			SELECT ERROR_NUMBER() AS ErrorNumber
		END CATCH
END 
GO